apiVersion: apps/v1
kind: Deployment
metadata:
  name: bgdeploy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: bgdeploy
  template:
    metadata:
      labels:
        name: bgdeploy
    spec:
      serviceAccountName: bgdeploy
      containers:
        - name: bgdeploy
          # Replace this with the built image name
          image: takeyan/bgdeploy-operator:0.0.1
          command:
          - bgdeploy
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "bgdeploy"
