kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bgdeploy
subjects:
- kind: ServiceAccount
  name: bgdeploy
roleRef:
  kind: Role
  name: bgdeploy
  apiGroup: rbac.authorization.k8s.io
